### ISSUE TITLE
emacs 26.1-h5d2cb88_0 depends on libtinfo.so.6, can't run on Ubuntu 16.04.4

### ISSUE THREAD

**Issue by lebedov** [conda-forge/emacs-feedstock#24] opened 2018-07-03 12:59 UTC
Issue: emacs 26.1-h5d2cb88_0 depends on libtinfo.so.6, which is not available on Ubuntu 16.04.4:

```
$ emacs -nw
emacs: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory  
```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/lebedov/miniconda3:
#
# Name                    Version                   Build  Channel
_tflow_180_select         1.0                         gpu  
absl-py                   0.2.2                      py_0    conda-forge
agate                     1.6.0                    py36_2    conda-forge
agate-dbf                 0.2.0                    py36_0    conda-forge
agate-excel               0.2.2                      py_0    conda-forge
agate-sql                 0.5.3                      py_0    conda-forge
aiodns                    1.1.1                     <pip>
aiohttp                   3.3.2            py36h14c3975_0    conda-forge
altair                    2.1.0                      py_0    conda-forge
altair-widgets            0.1.2                     <pip>
anaconda-client           1.6.14                     py_0    conda-forge
appdirs                   1.4.3                     <pip>
appdirs                   1.4.3                      py_1    conda-forge
applicationinsights       0.11.1                    <pip>
argparse                  1.4.0                     <pip>
arpack                    3.6.1           blas_openblas_0  [blas_openblas]  conda-forge
arrayfire                 3.6.0                     <pip>
asn1crypto                0.24.0                   py36_0    conda-forge
astor                     0.6.2                      py_0    conda-forge
astropy                   3.0.3                    py36_1    conda-forge
async-timeout             3.0.0                    py36_0    conda-forge
atomicwrites              1.1.5                    py36_0    conda-forge
attrs                     18.1.0                     py_1    conda-forge
autobahn                  18.6.1                     py_0    conda-forge
automat                   0.7.0                    py36_0    conda-forge
Automat                   0.6.0                     <pip>
babel                     2.6.0                    py36_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.csv             1.0.5                     <pip>
backports.csv             1.0.5                      py_1    conda-forge
backports.weakref         1.0rc1                   py36_1    conda-forge
bashplotlib               0.6.5                     <pip>
beakerx                   0.21.0                   py36_1    conda-forge
beautifulsoup4            4.6.0                    py36_0    conda-forge
binaryornot               0.4.4                     <pip>
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                    py36_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     0.12.16                  py36_0    conda-forge
boto                      2.48.0           py36h6e4cd66_1  
boto3                     1.7.48                     py_0    conda-forge
botocore                  1.10.48                    py_0    conda-forge
bqplot                    0.10.5                   py36_0    conda-forge
brewer2mpl                1.4.1                    py36_2    conda-forge
bz2file                   0.98                     py36_0  
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
cchardet                  2.1.1                    py36_0    conda-forge
cefpython3                57.0                      <pip>
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
cli-helpers               0.2.3                     <pip>
cli_helpers               1.0.2                      py_0    conda-forge
click                     6.7                        py_1    conda-forge
click                     6.7                       <pip>
cloudpickle               0.5.3                      py_0    conda-forge
clyent                    1.2.2                    py36_0    conda-forge
cmake                     3.11.4                        0    conda-forge
codecov                   2.0.15                     py_1    conda-forge
colorama                  0.3.9                    py36_0    conda-forge
colorlover                0.2.1                      py_0    conda-forge
complexity                0.9.1                     <pip>
conda                     4.5.5                    py36_0    conda-forge
conda-build               3.10.9                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
configobj                 5.0.6                     <pip>
constantly                15.1.0                     py_0    conda-forge
coverage                  4.5.1                    py36_0    conda-forge
cryptography              2.2.1            py36hdffb7b8_1    conda-forge
cssselect                 1.0.3                      py_0    conda-forge
csvkit                    1.0.2                    py36_0    conda-forge
cuda90                    1.0                  h6433d27_0    pytorch
cuda91                    1.0                  h4c16780_0    pytorch
cudatoolkit               9.0                  h13b8566_0  
cudnn                     7.1.2                 cuda9.0_0  
cufflinks                 0.12.1                    <pip>
cupti                     9.0.176                       0  
curl                      7.60.0                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cytoolz                   0.9.0.1                  py36_0    conda-forge
dask                      0.18.1                     py_0    conda-forge
dask-core                 0.18.1                     py_0    conda-forge
dbfread                   2.0.7                    py36_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
delegator                 0.1.0                    py36_0    conda-forge
dill                      0.2.8.2                  py36_0    conda-forge
distributed               1.22.0                   py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
duster                    0.2.5                     <pip>
emacs                     26.1                 h5d2cb88_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
et_xmlfile                1.0.1                    py36_0    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
fast-histogram            0.3                      py36_0    conda-forge
feedfinder2               0.0.4                      py_0    conda-forge
feedparser                5.2.1                    py36_0  
ffmpeg                    4.0                  hc8c182b_0    conda-forge
fftw                      3.3.7                         0    conda-forge
filelock                  3.0.4                    py36_0    conda-forge
flask                     1.0.2                      py_1    conda-forge
flatdict                  2.0.1                     <pip>
fontconfig                2.12.6                        0    conda-forge
freetds                   1.00.44                       2    conda-forge
freetype                  2.8.1                         0    conda-forge
future                    0.16.0                    <pip>
gast                      0.2.0                      py_0    conda-forge
geckodriver               0.21.0               hfc679d8_0    conda-forge
gensim                    3.4.0                    py36_0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
gevent                    1.3a1                    py36_0    conda-forge
giflib                    5.1.4                h470a237_0    conda-forge
glib                      2.55.0                        0    conda-forge
glob2                     0.6                        py_0    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gnutls                    3.5.17                        0    conda-forge
gpmf-0.0.1dev-b-5197623-n                           <pip>
gr                        1.0.1                     <pip>
graphite2                 1.3.11               hfc679d8_0    conda-forge
greenlet                  0.4.13                   py36_0    conda-forge
grequests                 0.3.0                    py36_0    conda-forge
grpcio                    1.12.1           py36hdbcaa40_0  
gsl                       2.4             blas_openblas_0  [blas_openblas]  conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
h2o                       3.18.0.2                      0  
h5py                      2.8.0            py36hb794570_1    conda-forge
harfbuzz                  1.7.6                         0    conda-forge
hdf5                      1.10.2                        0    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
holoviews                 1.10.6                     py_0    conda-forge
html5lib                  0.9999999                py36_0    conda-forge
httmock                   1.2.6                     <pip>
http-request-randomizer   1.2.1                     <pip>
httpstream                1.3.0                     <pip>
humanize                  0.5.1                     <pip>
hyperlink                 17.3.1                     py_0    conda-forge
icdiff                    1.9.1                     <pip>
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py36_0    conda-forge
idna_ssl                  1.0.0                         0    conda-forge
imageio                   2.3.0                    py36_0    conda-forge
incremental               17.5.0                     py_0    conda-forge
intel-openmp              2018.0.3                      0  
ipdb                      0.11                     py36_0    conda-forge
ipdbplugin                1.5.0                     <pip>
ipyk                      0.1.4.2                   <pip>
ipykernel                 4.8.2                    py36_0    conda-forge
ipympl                    0.2.0                    py36_0    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython-sql               0.3.9                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.2.1                    py36_1    conda-forge
isodate                   0.6.0                      py_0    conda-forge
itsdangerous              0.24                       py_2    conda-forge
jdcal                     1.4                      py36_0    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jieba3k                   0.35.1                   py36_1    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jmespath                  0.9.3                    py36_0    conda-forge
joblib                    0.12                       py_0    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jsonstream                1.0.0                     <pip>
julia                     0.6.1           blas_openblas_202  [blas_openblas]  conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                    py36_0    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_contrib_core      0.3.3                    py36_1    conda-forge
jupyter_contrib_nbextensions 0.5.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                    py36_0    conda-forge
jupyter_latex_envs        1.4.4                    py36_0    conda-forge
jupyter_nbextensions_configurator 0.4.0                    py36_0    conda-forge
jupyterlab                0.32.1                   py36_0    conda-forge
jupyterlab_launcher       0.10.5                   py36_0    conda-forge
keras                     2.1.6                    py36_0    conda-forge
Keras                     2.1.2                     <pip>
keras-anomaly-detection   0.0.1                     <pip>
kiwisolver                1.0.1                    py36_1    conda-forge
kraken                    0.9.18.dev3               <pip>
krb5                      1.14.6                        0    conda-forge
leather                   0.3.3                    py36_0    conda-forge
libedit                   3.1.20170329                  0    conda-forge
libevent                  2.0.22               hdffb7b8_1    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libgit2                   0.27.2               h2a9243c_0    conda-forge
libgpuarray               0.7.6                         0    conda-forge
libiconv                  1.15                 h470a237_1    conda-forge
libidn11                  1.33                          0    conda-forge
libpng                    1.6.34               ha92aebf_1    conda-forge
libprotobuf               3.5.2                hd28b015_1    conda-forge
libsodium                 1.0.16                        0    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he6b73bb_1    conda-forge
libuuid                   1.0.3                         1    conda-forge
libuv                     1.20.3                        0    conda-forge
libxcb                    1.13                 h470a237_0    conda-forge
libxml2                   2.9.8                h422b904_1    conda-forge
libxslt                   1.1.32               h88dbc4e_1    conda-forge
lmdb                      0.93                      <pip>
locket                    0.2.0                    py36_1    conda-forge
lxml                      4.2.2            py36hc9114bc_0    conda-forge
magma                     2.3.0                  cuda91_0    local
magma-cuda90              2.3.0                         1    pytorch
magma-cuda91              2.3.0                         1    pytorch
mako                      1.0.7                    py36_0    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
maven                     3.5.0                         0    conda-forge
metis                     5.1.0                         3    conda-forge
mistune                   0.8.3                    py36_1    conda-forge
mkl                       2018.0.3                      1  
more-itertools            4.2.0                      py_0    conda-forge
moviepy                   0.2.3.5                    py_0    conda-forge
mpfr                      3.1.5                         0    conda-forge
mpl-scatter-density       0.3                      py36_0    conda-forge
mplcursors                0.1                       <pip>
mpldatacursor             0.6.2                     <pip>
msgpack-numpy             0.4.2                     <pip>
msgpack-python            0.5.6            py36h2d50403_2    conda-forge
mssql-cli                 0.9.0                     <pip>
multidict                 4.3.1            py36h470a237_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
nettle                    3.3                           0    conda-forge
networkx                  2.1                      py36_0    conda-forge
newspaper3k               0.2.6                     <pip>
newspaper3k               0.2.6                    py36_0    conda-forge
ninja                     1.8.2                h2d50403_1    conda-forge
nltk                      3.2.5                      py_0    conda-forge
nodeenv                   1.3.1                      py_0    conda-forge
nodejs                    9.11.1                        0    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.5.0                    py36_0    conda-forge
numpy                     1.14.5          py36_blas_openblashd3ea46f_200  [blas_openblas]  conda-forge
oauthlib                  2.1.0                      py_0    conda-forge
objbrowser                1.2.1                     <pip>
olefile                   0.45.1                   py36_0    conda-forge
oneliner                  0.2.1                     <pip>
openblas                  0.2.20                        8    conda-forge
openjdk                   8.0.121                       1  
openlibm                  0.5.4                         0    conda-forge
openpyxl                  2.5.4                    py36_0    conda-forge
openspecfun               0.5.3                         0    conda-forge
openssl                   1.0.2o                        0    conda-forge
owlpy                     1.0.0                     <pip>
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.1                   py36_0    conda-forge
pandoc                    2.2.1                         0    conda-forge
pandocfilters             1.4.2                    py36_0    conda-forge
panflute                  1.10.6                    <pip>
pango                     1.40.14                       0    conda-forge
pantable                  0.11.1                    <pip>
param                     1.6.1                      py_0    conda-forge
parsedatetime             2.4                      py36_0    conda-forge
parso                     0.3.0                      py_0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
patchelf                  0.9                           2    conda-forge
path.py                   11.0.1                     py_0    conda-forge
patsy                     0.5.0                    py36_0    conda-forge
pbr                       4.0.4                      py_0    conda-forge
pcre                      8.41                          1    conda-forge
pcre2                     10.23                         2    conda-forge
perl                      5.22.2.1                      0    conda-forge
perspective-python        0.0.6                     <pip>
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    5.2.0                    py36_0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0                        2    conda-forge
pkginfo                   1.4.2                    py36_0    conda-forge
plotly                    2.7.0                      py_1    conda-forge
pluggy                    0.6.0                      py_0    conda-forge
pluggy                    0.6.0                     <pip>
powerline-gitstatus       1.2.1                     <pip>
powerline-status          2.6                       <pip>
prettytable               0.7.2                    py36_1    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
protobuf                  3.5.2                    py36_0    conda-forge
psutil                    5.4.3                     <pip>
psutil                    5.4.6                    py36_0    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
py                        1.5.4                      py_0    conda-forge
py                        1.5.2                     <pip>
py2neo                    3.1.2                     <pip>
py4j                      0.10.7                   py36_0    conda-forge
pyasn1                    0.4.3                      py_0    conda-forge
pyasn1-modules            0.2.1                      py_0    conda-forge
pycares                   2.3.0                     <pip>
pycosat                   0.6.3                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pycuda                    2017.1.1                  <pip>
pydensecrf                1.0rc3           py36hf8a1672_1    conda-forge
pydot                     1.2.4                      py_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pygpu                     0.7.6                    py36_0    conda-forge
pyjwt                     1.6.4                      py_0    conda-forge
pylantern                 0.0.17                    <pip>
pymssql                   2.1.3.post16             py36_0    conda-forge
pyodbc                    4.0.17                   py36_0    conda-forge
pyopengl                  3.1.1a1                  py36_0    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_5    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
pysolr                    3.6.0                    py36_0    conda-forge
pytest                    3.6.2                    py36_0    conda-forge
pytest-arraydiff          0.2                        py_0    conda-forge
pytest-astropy            0.2.1                      py_0    conda-forge
pytest-cov                2.5.1                    py36_0    conda-forge
pytest-doctestplus        0.1.2                      py_0    conda-forge
pytest-openfiles          0.2.0                      py_0    conda-forge
pytest-remotedata         0.3.0                      py_0    conda-forge
python                    3.6.5                         1    conda-forge
python-bidi               0.4.0                    py36_0    conda-forge
python-crfsuite           0.9.5            py36h470a237_0    conda-forge
python-dateutil           2.6.1                     <pip>
python-dateutil           2.7.3                      py_0    conda-forge
python-slugify            1.2.5                    py36_0    conda-forge
pytimeparse               1.1.8                      py_0    conda-forge
pytools                   2018.5.2                   py_0    conda-forge
pytorch                   0.4.0           py36_cuda9.1.85_cudnn7.1.2_1  [cuda91]  pytorch
pytz                      2018.5                     py_0    conda-forge
pyviz_comms               0.1.1                      py_0    conda-forge
pywavelets                0.5.2                    py36_1    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
PyYAML                    3.12                      <pip>
pyzmq                     17.0.0                   py36_4    conda-forge
qgrid                     1.0.5                    py36_1    conda-forge
qt                        5.6.2                         7    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
qtpy                      1.4.2            py36h8a2030e_0    conda-forge
readline                  7.0                           0    conda-forge
regex                     2018.06.21       py36h470a237_0    conda-forge
requests                  2.19.1                   py36_0    conda-forge
requests-file             1.4.3                    py36_0  
requests-oauthlib         0.8.0                    py36_1    conda-forge
requests-toolbelt         0.8.0                    py36_0    conda-forge
rhash                     1.3.4                         0    conda-forge
ruamel_yaml               0.15.40          py36h470a237_0    conda-forge
s3transfer                0.1.13                   py36_0    conda-forge
sarge                     0.1.4                    py36_0    conda-forge
saxpy                     1.0.1.dev169              <pip>
schedule                  0.5.0                     <pip>
scikit-cuda               0.5.2                     <pip>
scikit-image              0.14.0           py36hfc679d8_1    conda-forge
scikit-learn              0.19.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.1.0           py36_blas_openblas_200  [blas_openblas]  conda-forge
seaborn                   0.8.1                    py36_0    conda-forge
selenium                  3.12.0                   py36_0    conda-forge
semisup-learn             0.0.1                     <pip>
send2trash                1.5.0                      py_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setproctitle              1.1.10                    <pip>
setuptools                39.2.0                   py36_0    conda-forge
shutilwhich               1.1.0                     <pip>
simplegeneric             0.8.1                    py36_0    conda-forge
simplejson                3.16.0                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sklearn                   0.0                       <pip>
smart_open                1.6.0                    py36_0    conda-forge
sortedcontainers          2.0.4                    py36_0    conda-forge
spam-classifier           0.1.0                     <pip>
sqlalchemy                1.2.9                    py36_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
sqlparse                  0.2.4                      py_0    conda-forge
sqlparse                  0.2.4                     <pip>
statsmodels               0.9.0                    py36_0    conda-forge
suitesparse               4.5.6           blas_openblas_200  [blas_openblas]  conda-forge
tabview                   1.4.3                     <pip>
tbb                       2018_20171205                 0    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
tensorboard               1.8.0                    py36_1    conda-forge
tensorflow                1.8.0                    py36_1    conda-forge
tensorflow-gpu            1.8.0                h7b35bdc_0  
tensorflow-gpu-base       1.7.0            py36hcdda91b_1  
tensorflow-tensorboard    1.5.1            py36hf484d3e_1  
termcolor                 1.1.0                    py36_1    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
terminaltables            3.1.0                      py_0    conda-forge
terminaltables            3.1.0                     <pip>
testpath                  0.3.1                    py36_0    conda-forge
theano                    1.0.2                    py36_0    conda-forge
tig                       2.3.3                         0    local
tk                        8.6.7                         0    conda-forge
tldextract                2.2.0                      py_0    conda-forge
tmux                      2.7                           0    conda-forge
toolz                     0.9.0                      py_0    conda-forge
torchfile                 0.1.0                     <pip>
torchvision               0.2.1                    py36_1    pytorch
tornado                   5.0.2                    py36_0    conda-forge
tqdm                      4.23.4                     py_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
traittypes                0.2.1                    py36_0    conda-forge
twine                     1.10.0                   py36_0    conda-forge
twisted                   17.5.0                   py36_0  
twython                   3.7.0                      py_0    conda-forge
txaio                     2.10.0                     py_0    conda-forge
typing                    3.6.4                    py36_0    conda-forge
ujson                     1.35                     py36_0    conda-forge
unidecode                 1.0.22                   py36_0    conda-forge
unixodbc                  2.3.4                         1    conda-forge
urllib3                   1.23                     py36_0    conda-forge
vega                      1.3.0                    py36_0    conda-forge
vega-datasets             0.4.1                     <pip>
visdom                    0.1.8.3                   <pip>
watson-developer-cloud    1.2.1                     <pip>
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
websocket-client          0.48.0                     py_0    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
widgetsnbextension        3.2.1                    py36_0    conda-forge
x264                      20131218                      0    conda-forge
xgboost                   0.72                     py36_0    conda-forge
xlrd                      1.1.0                      py_2    conda-forge
xorg-fixesproto           5.0                           1    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                         2    conda-forge
xorg-libsm                1.2.2                         2    conda-forge
xorg-libx11               1.6.5                         0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxaw               1.0.13                        0    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xorg-libxext              1.3.3                         2    conda-forge
xorg-libxfixes            5.0.3                         2    conda-forge
xorg-libxmu               1.1.2                         0    conda-forge
xorg-libxpm               3.5.12                        0    conda-forge
xorg-libxt                1.1.5                         0    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                         0    conda-forge
yarl                      1.2.6            py36h470a237_0    conda-forge
yolk3k                    0.9                       <pip>
zeromq                    4.2.5                         1    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
zope                      1.0                      py36_0  
zope.interface            4.5.0            py36h470a237_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : /home/lebedov/miniconda3
            shell level : 1
       user config file : /home/lebedov/.condarc
 populated config files : /home/lebedov/.condarc
          conda version : 4.5.5
    conda-build version : 3.10.9
         python version : 3.6.5.final.0
       base environment : /home/lebedov/miniconda3  (writable)
           channel URLs : file:///home/lebedov/miniconda3/conda-bld/linux-64
                          file:///home/lebedov/miniconda3/conda-bld/noarch
                          https://conda.anaconda.org/lebedov/linux-64
                          https://conda.anaconda.org/lebedov/noarch
                          https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/lebedov/miniconda3/pkgs
                          /home/lebedov/.conda/pkgs
       envs directories : /home/lebedov/miniconda3/envs
                          /home/lebedov/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.5 requests/2.19.1 CPython/3.6.5 Linux/4.15.0-24-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by asmeurer** [comment] 2018-07-03 17:09
I thought libtinfo was supposed to be part of the ncurses package. @jakirkham do you know how what is happening here? I get the same problem on OS X too:

```
dyld: Library not loaded: @rpath/libtinfo.6.dylib
  Referenced from: /Users/aaronmeurer/anaconda3/Emacs.app/Contents/MacOS/Emacs
  Reason: image not found
/Users/aaronmeurer/anaconda3/bin/emacs: line 2: 18601 Abort trap: 6           /Users/aaronmeurer/anaconda3/Emacs.app/Contents/MacOS/Emacs "$@"
```

**Comment by asmeurer** [comment] 2018-07-03 18:06
Ah it requires ABI version 6, but the ncurses package includes version 5. There must be a newer ncurses which is installed on Travis and Circle, and somehow it's building against that.

**Comment by jakirkham** [comment] 2018-07-03 18:19
xref: https://github.com/conda-forge/emacs-feedstock/pull/23#issuecomment-402248958

**Comment by asmeurer** [comment] 2018-07-03 18:58
Thanks. https://github.com/conda-forge/emacs-feedstock/pull/25. It would probably be worth improving the wording about that in the command, if not doing a rerender automatically. CC @CJ-Wright

**Comment by CJ-Wright** [comment] 2018-07-03 19:11
@isuruf would it be possible to force a re-render as part of the cb3 command?

**Comment by asmeurer** [comment] 2018-07-06 22:23
@lebedov can you check if this works for you now?

**Comment by asmeurer** [comment] 2018-07-06 22:35
I can confirm that the OS X build is fixed.

**Comment by lebedov** [comment] 2018-07-08 03:05
@asmeurer emacs-26.1-h3a2ea38_1 still doesn't work on Linux (same problem). 

Not sure whether if it matters, but I had to manually download it from anaconda.org because it isn't showing up in the output of `conda search emacs` as of the present.

**Comment by asmeurer** [comment] 2018-07-08 03:07
Hm. I don't know why it doesn't show up. Do you have conda-forge in your channels list (`conda info`)? 

Anyway, I don't know how conda handles dependencies for manually downloaded files these days. Can you try installing it into a new test environment, and showing me `conda list`?

**Comment by lebedov** [comment] 2018-07-08 06:02
Yes - conda-forge is in my channel list; here is the output of `conda info`:

```
active environment : base
    active env location : /home/lebedov/miniconda3
            shell level : 1
       user config file : /home/lebedov/.condarc
 populated config files : /home/lebedov/.condarc
          conda version : 4.5.6
    conda-build version : 3.10.9
         python version : 3.6.5.final.0
       base environment : /home/lebedov/miniconda3  (writable)
           channel URLs : file:///home/lebedov/miniconda3/conda-bld/linux-64
                          file:///home/lebedov/miniconda3/conda-bld/noarch
                          https://conda.anaconda.org/lebedov/linux-64
                          https://conda.anaconda.org/lebedov/noarch
                          https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/lebedov/miniconda3/pkgs
                          /home/lebedov/.conda/pkgs
       envs directories : /home/lebedov/miniconda3/envs
                          /home/lebedov/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.6 requests/2.19.1 CPython/3.6.5 Linux/4.15.0-24-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

Creating a new conda environment via `conda create -n EMACS emacs` installed the appropriate dependencies needed to enable emacs to run.

**Comment by asmeurer** [comment] 2018-07-08 06:09
> Creating a new conda environment via conda create -n EMACS emacs installed the appropriate dependencies needed to enable emacs to run.

I guess that means the pinning isn't actually working (the package should require ncurses to update to 6 to be installed).

**Comment by asmeurer** [comment] 2018-07-08 06:11
No, nevermind. I downloaded the file and checked the `info/index.json` and 

```
{
  "arch": "x86_64",
  "build": "h3a2ea38_1",
  "build_number": 1,
  "depends": [
    "freetype >=2.8.1,<2.9.0a0",
    "giflib >=5.1.4,<5.2.0a0",
    "gnutls",
    "jpeg >=9c,<10a",
    "libgcc-ng >=4.9",
    "libpng >=1.6.34,<1.7.0a0",
    "libtiff >=4.0.9,<5.0a0",
    "libxml2 >=2.9.8,<2.10.0a0",
    "ncurses >=6.1,<6.2.0a0",
    "xorg-libxaw",
    "xorg-libxfixes",
    "xorg-libxpm",
    "zlib >=1.2.11,<1.3.0a0"
  ],
  "license": "GPL-3.0",
  "name": "emacs",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1530915678683,
  "version": "26.1"
}
```

Did installing `emacs` in your main environment update ncurses to 6? If it is installed, maybe it is broken somehow (`conda install -f ncurses` would fix it).

**Comment by lebedov** [comment] 2018-07-08 06:15
I do have some other packages such as tmux that depend on ncurses 5.9 in the environment in which I was encountering problems - perhaps that was confusing conda when I tried to install the latest emacs package? (I submitted a request to [rebuild tmux against ncurses 6.1](https://github.com/conda-forge/tmux-feedstock/issues/8).)

**Comment by asmeurer** [comment] 2018-07-08 06:16
I can confirm in a Docker container that 

```
conda create -n test ncurses=5
conda install -n test emacs
```

installs the old, broken build, but

```
conda create -n test emacs
```

installs the latest build (and emacs does work in that build).  Does conda auto-pin ncurses since I used it to create the environment?

**Comment by asmeurer** [comment] 2018-07-08 06:16
Ah yes, so try

```
conda install emacs ncurses=6
```

and that will force it to install ncurses=6, or fail if it's impossible (or it might uninstall tmux, you might want to try it with `--dry-run` first to see what it does).

**Comment by lebedov** [comment] 2018-07-08 06:17
When I tried installing emacs in my main environment, conda tried to install 26.1-h5d2cb88_0

**Comment by lebedov** [comment] 2018-07-08 06:21
Running `conda install emacs ncurses=6` in my main environment tries to install emacs-26.1-h3a2ea38_1 and uninstall tmux.

**Comment by asmeurer** [comment] 2018-07-08 14:33
Ok so that's the problem. I think this package works fine. We should probably remove the older build from anaconda.org. I wish conda didn't try to install older builds by default.

**Comment by asmeurer** [comment] 2018-07-11 21:53
OK, now when I install emacs, it doesn't install ncurses (but when I create a new environment with it, it does).

**Comment by lebedov** [comment] 2018-07-12 04:17
When I create a new environment that doesn't contain emacs 26.1-h3a2ea38_1 or ncurses 6.1-0 and try to install emacs, it installs both of the above packages.

**Comment by asmeurer** [comment] 2018-07-15 17:01
OK, I figured out the problem. The `defaults` ncurses doesn't have the versioned libtinfo.so.6 (it only has libtinfo.so). CC @msarahan

**Comment by asmeurer** [comment] 2018-07-27 18:11
Can we pin ncurses to the conda-forge channel in the meantime?

**Comment by ipstone** [comment] 2018-10-25 16:57
Hello everybody, is this issue resolved? I just installed emacs from conda forge, still get the same error:
`emacs: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory`

**Comment by asmeurer** [comment] 2018-10-25 19:21
@ipstone the issue is with the upstream `ncurses` package from Anaconda. The fix for this is to run `conda update ncurses`. 

CC @conda-forge/core how can we pin `ncurses` in this package to the conda-forge one until they fix this upstream?

**Comment by ghost** [comment] 2018-11-22 13:37
@asmeurer I installed miniconda on an amazon ami. Installed pandas. Then installed emacs. Tried to run emacs and I get this error. conda update ncurses didn't fix it.

**Comment by asmeurer** [comment] 2018-11-27 18:33
What version of ncurses does it install? If you manually install the package from conda-forge it should fix the issue.

**Comment by jjhelmus** [comment] 2018-11-28 22:51
The latest build of ncurses 6.1 (1) in `defaults` includes symlinks for the versioned non-wide libraries (e.g. libtinfo.so.6).  I should improve compatibility with the conda-forge version.

**Comment by asmeurer** [comment] 2018-11-28 23:13
Was that just released? I think that should fix this issue.

**Comment by jjhelmus** [comment] 2018-11-28 23:48
Yes, the new build was added to the repository today.

**Comment by asmeurer** [comment] 2018-11-29 19:06
I tested it in a Linux VM. By default, `conda create -n test emacs` installs the conda-forge ncurses, but if I manually install the latest defaults one (`6.1=he6710b0_1`) emacs still works.

**Closed as completed by asmeurer** 2018-11-29 19:06 UTC
